version: '3.7'
services:
   mysql:
     build: ./mysql
     container_name: mysql
     ports:
      - "3306:3306"
     restart: always
     volumes:
       - mysql_data:/var/lib/mysql
     environment:
       - MYSQL_ROOT_PASSWORD=root       
   phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpMyAdmin
    depends_on:
      - mysql
    links:
      - mysql
    environment:
     PMA_HOST: mysql
     PMA_PORT: 3306
     UPLOAD_LIMIT: 300M
    ports:
      - "8080:80"
    restart: always
volumes:
  mysql_data:
